yolov8_sv_gps_save_node:
  ros__parameters:
    model_path: "/home/nvidia/weight/Competition_2025.pt"
    device: "cuda:0"
    imgsz: 640
    conf_thresh: 0.25
    camera_source: "rtsp://user:user@192.168.168.108:554/cam/realmonitor?channel=1&subtype=0"
    rtsp_server_url: "rtsp://192.168.168.12:8554/live/stream"
    frame_rate: 20
    gps_topic: "/target_position"
    save_directory: "/home/nvidia/Yolov8-Video"
    base_filename: "Yolov8-Recording.mp4"
    