yolov8_sv_gps_node:
  ros__parameters:
    model_path: "/home/fantasywilly/weight/Competition_2025.pt"
    device: "cuda:0"
    imgsz: 640
    conf_thresh: 0.25
    camera_source: "rtsp://root:12345@192.168.1.10/stream=0"
    rtsp_server_url: "rtsp://192.168.0.230:8554/live/stream"
    frame_rate: 30